### ISSUE TITLE
Easiest way to send an array for a PATCH request

### ISSUE THREAD

**Issue by samstarling** [flexirest/flexirest#102]
@andyjeffries I have an API that expects an array of operations for a PATCH request. For example `PATCH /users/123` with a body of:

```
[
  { operation: 'update', field: 'first_name', value: 'Sam' },
  { operation: 'update', field: 'last_name', value: 'Starling' }
]
```

Is there a good way to have this work with Flexirest? Having `patch :update, '/users/:id'` and then calling `User.find(1).update([ { operation: 'update' } ])` results in a PATCH request being sent to the right URL but with a body of `{}`.

**Comment by andyjeffries** [comment]
The only way I can think of is using a `before_request` callback to replace the body with your own custom parsed version (https://github.com/flexirest/flexirest/blob/master/docs/using-callbacks.md). You'd then need to pass in something like:

```
User.find(1).update(operations: [{ operation: 'update'}])
```

**Comment by samstarling** [comment]
Thanks – that makes sense. I'll have a play around and see what I come up with!
