### ISSUE TITLE
Do associations call the nested resource?

### ISSUE THREAD

**Issue by noctivityinc** [flexirest/flexirest#106]
@andyjeffries sorry for all these issue posts but either the docs are confusing  / wrong or Im simply doing something wrong.

Associations...

I have the following models:

```
class SiteKey < Flexirest::Base

  verbose!

  before_request do |name, request|
    request.headers["Authorization"] = "Bearer: #{Current.token}"
  end 

  get :all, "/admin/site/:site_id/keys", ignore_root: 'keys'
  get :find, "/admin/site/:site_id/keys/:id", ignore_root: 'keys'
  put :save, "/admin/site/:site_id/keys/:id", wrap_root: 'site_key'
  post :create, "/admin/site/:site_id/keys", wrap_root: 'site_key'
  delete :destroy, "/admin/site/:site_id/keys/:id"

end
```

```
class Site < Flexirest::Base

  verbose!

  before_request do |name, request|
    request.headers["Authorization"] = "Bearer: #{Current.token}"
  end

  has_many :site_keys, SiteKey

  get :all, "/admin/sites", ignore_root: 'sites'
  get :find, "/admin/sites/:id"
  put :save, "/admin/sites/:id", wrap_root: 'site'
  post :create, "/admin/sites", wrap_root: 'site'
  delete :destroy, "/admin/sites/:id"

end
```

Now when I call `site = Site.find(2)` this works perfectly.  I can see the request made to my API and all is well.  The response *does not* include any of the site keys, it only includes directly attributes about the Site.

I then try to get a list of the keys like this `site.site_keys` or `site.site_keys.all` and I get `nil` every time!?  What am I missing here?  I'm expecting it to make a request based on the definitions in the SiteKey class but it doesnt happen.

If I directly call `SiteKey.all(site_id: 2)` that works fine, but that's not conventional.  Am I missing something?

**Comment by andyjeffries** [comment]
The relationships functionality doesn't do anything about pulling other results, only in determining what class to instantiate for those attributes rather than itself. Hope that helps explain it.
