### ISSUE TITLE
Option ignore_root supporting array

### ISSUE THREAD

**Issue by gkosmr** [flexirest/flexirest#114]
Would it be possible to extend `ignore_root` option so that it accepts array of strings instead of just one string?

Use case:  I'm using an API that always returns the data in the following format:
```
{
	"response": {
		"meta": {},
		"data": []
	}
}
```
(So i actually somehow have a multi-level root but only one level is supported.)

The option in my case would then be used as: `get :all, '/all', ignore_root: ["response", "data"]`.

What do you think?

**Comment by andyjeffries** [comment]
Thanks for this, nice work - merged. It’s my birthday today so I’m going to be slammed busy, but will release a new version next week.
