### ISSUE TITLE
Presence of path parameters should be validated when preparing URLs

### ISSUE THREAD

**Issue by m-kind** [flexirest/flexirest#116]
### Actual behaviour

When I define my requests e.g. like this:

```ruby
  class User < Flexirest::Base
    get :all, "/users", ignore_root: "data"
    get :find, "/users/:uuid"
  end
```

and I call `User.find(uuid: nil)` (or `User.find(1)`) then I get the same result as when calling Users.all (except for the root `data` not being ignored). It appears like flexirest does not validate the presence of path parameters that are part of the defined path and thus produces unexpected request URLs.

### Expected behaviour

If a path parameter is not available
- as a non-blank method parameter
- or as a non-blank object attribute (if no method parameter has been passed in)

the call should raise an exception as it is not able to compute the correct URL from the information being available.

It might be enough to check for `target` being present in `lib/flexirest/request.rb:371` and raise an exception if not.

**Comment by andyjeffries** [comment]
Thanks for the excellent bug report, I've just released 1.8.7 to resolve this because I agree, it's definitely not expected.
