### ISSUE TITLE
cleanup of forced response cache

### ISSUE THREAD

**Issue by m4c3** [flexirest/flexirest#130]
Hey,
i ran into a similar situation like #113 and ended up creating callback functions like this for the cleanup of the cache.

```ruby
class Whatever < Flexirest::Base
  after_request :cache
  before_request :cache_cleanup

  get :get, '/whatever/:id'
  post :update, '/whatever/:id'
  delete :delete, '/whatever/:id'

  def cache_cleanup(name, request)
    if name == :update || name == :delete
      Flexirest::Logger.info("  \033[1;4;32m#{Flexirest.name}\033[0m #{self.class.name}:#{request.url} - remove from cache")
      Rails.cache.delete("#{self.class.name}:#{request.url}")
    end
  end

  def cache(name, response)
    if name == :get
      response.response_headers["Expires"] = 1.hour.from_now.iso8601
    end
  end
end
```

does it make sense to update the cache_all_people example in https://github.com/flexirest/flexirest/blob/master/docs/using-callbacks.md or maybe https://github.com/flexirest/flexirest/blob/master/docs/caching.md with this cleanup method?

**Comment by andyjeffries** [comment]
Good tip, I've added it to the documentation now. Thank you 👍

**Comment by xiaoboa** [comment]
There is one trap with this solution, the `Rails.cache.delete` will return `false` when no cache is deleted. 

According to [using-callback](https://github.com/flexirest/flexirest/blob/master/docs/using-callbacks.md)
> If you want to cancel the request from within a callback, you can simply return false and the mapped method result will also be false,

This will cancel the request(.e.g. update) when no cache is deleted

**Comment by andyjeffries** [comment]
Thanks @xiaoboa - updated the documentation to explicitly return nil always from the cache cleanup method.
