### ISSUE TITLE
Possible to ignore/wrap root for all routes?

### ISSUE THREAD

**Issue by aharpervc** [flexirest/flexirest#134]
### Expected behaviour

I'd like to be able to set ignore/wrap root for all methods on an API. Currently this throws an exception due to those helper methods applying to route method definitions.

### Desired behaviour

Doing this (as in the example) should automatically apply to all routes by default

### How to reproduce

1. Clone the Flexirest repo (`git clone https://github.com/flexirest/flexirest.git`)
2. Change to the flexirest folder (`cd flexirest`)
3. Install any dependencies (`bundle install`)
4. Run an interactive console (`rake c`)
5. Paste the following:

```ruby
class ModelBase < Flexirest::Base
  # question is about this vvv
  ignore_root 'data'
  wrap_root 'data'

  # other setup, works fine
  request_body_type :json

end

class ThingModel < ModelBase
  base_url 'https://example.com/api/things'
  get :find
  # http response as this
  # { 'data': { 'id': 1 } }
end

ThingModel.find(1) # automatically ignores/wraps 'data'
```

The workaround is to write this as the docs say, eg

```ruby
get :find, ignore_root: 'data' # etc
```

**Comment by andyjeffries** [comment]
Seems like a great idea, sorry it's taken me a while to review it.

Time is super tight for me at the moment, so I'll either have a look at this after New Year, or feel free to have a go and raise a Pull Request and I can provide feedback on that?

Thanks.

**Comment by sampatbadhe** [comment]
@andyjeffries @aharpervc I wish to work on this, let know if you want me to go for it.

**Comment by andyjeffries** [comment]
Absolutely, PRs are always welcome. Please go for it!

**Comment by sampatbadhe** [comment]
@andyjeffries I have raised the [PR](https://github.com/flexirest/flexirest/pull/137). Could you please take look?

I will update the documentation once the changes look good.
