### ISSUE TITLE
Feature request: Basic Auth in header instead of URL

### ISSUE THREAD

**Issue by francois-ferrandis** [flexirest/flexirest#138]
### Expected behaviour

When I use `username` / `password` for Basic Auth, I expect it to use the credentials to build a Base64 header. Instead, it inserts the credentials at the beginning of the URL in clear.

### Desired behaviour

I would wish to use the header method so my credentials would not appear in my logs. Does that sound reasonable? 

### How to reproduce

There are already a few tests for the existing behaviour: https://github.com/flexirest/flexirest/blob/9c3c7cfc39784852f08126d00754f7f050f0f956/spec/lib/request_spec.rb#L236

### Proposition

Perhaps we could add an option to use the header method instead of the URL method. Something like that:

```ruby
username "john"
password "123456"
basic_auth_method :header # could be :header or :url
```

I already looked it up and started the implementation and tests, I think I can do it.

What do you think? :grinning:

**Comment by andyjeffries** [comment]
I like the idea of the change, as long as the default `basic_auth_method` stays the same as currently (we don't want to break existing sites using this code). Look forward to the PR! Thank you.
