### ISSUE TITLE
Spammy Wiki Page?

### ISSUE THREAD

**Issue by chriscz** [flexirest/flexirest#154]
Hi @andyjeffries, is this wiki page intentional, or is it spam? 

https://github.com/flexirest/flexirest/wiki/Automated-test-and-generate-RESTful-API-documentation-through-rest-client

**Comment by andyjeffries** [comment]
Whoah! Hadn't seen that before and no idea how it had got on there. I'm the only user with commit access (or any access) to the project. Thanks for letting me know, it's gone now.
