### ISSUE TITLE
Flexirest always logs the request made as log level info

### ISSUE THREAD

**Issue by mujtabamxht** [flexirest/flexirest#157]
### Expected behaviour

With the default value for verbose as false, I don't need flexirest to log any data regarding the request made, but it does.

### Desired behaviour

It should not call logger.info for all the requests made as that adds unnecessary logs on our log-stream e.g NewRelic

### How to reproduce

Make any API call within your codebase that has flexirest configure and notice how every request made gets logged.
This here https://github.com/flexirest/flexirest/blob/master/lib/flexirest/request.rb#L566 is the reason that happens

**Comment by andyjeffries** [comment]
I think that there should in theory be three levels:

1. Verbose logging - every request in and out, all headers, all bodies, etc (for debugging)
2. Normal logging - a note of every request sent, time taken, etc (like ActiveRecord's query logs)
3. Quiet logging - only log 4xx/5xx errors

So would you be happy with a `quiet!` equivalent to `verbose!` to put it in the third mode?

**Comment by mujtabamxht** [comment]
But, if you think `Quiet logging - only log 4xx/5xx errors` can be a quick fix/upgrade we are happy to use that flag

**Comment by andyjeffries** [comment]
Can you check out our master branch in your project please, if it's OK I'll tag a release. We didn't log exceptions normally, just raised them and left them to the client codebase to handle, so actually that wasn't necessary.

https://github.com/flexirest/flexirest/blob/master/docs/logging.md#quiet

**Comment by mujtabamxht** [comment]
Just gave it a try, it is working great with no logging for modules I set `quiet!`. Thanks for the quick resolution @andyjeffries

Are you going to release a new tag/version soon or should I point flexirest within my Gemfile to the master branch?

**Comment by andyjeffries** [comment]
v1.10.12 is out now with this in.
