### ISSUE TITLE
[AttributeParsing] TypeError: no implicit conversion of DateTime into String

### ISSUE THREAD

**Issue by johnmckinght** [flexirest/flexirest#48]
hi,
flexirest fail while trying to read respond from cache. the error occur in _flexirest/attribute_parsing.rb_
below is rails console verbose output

>> TodoUser.find(1)
  Flexirest TodoUser:/users/1 - Trying to read from cache
  Flexirest TodoUser#find - Requesting http://dev0.todo.org/api/v1/users/1
Flexirest Verbose Log:
  Request
  >> GET /api/v1/users/1 HTTP/1.1
  >> Accept : application/hal+json, application/json;q=0.5
  >> Authorization : Token token=[redacted],email=admin@todo.org
  >> Content-Type : application/json; charset=utf-8
  >> Body:
{}
  Response
  << Status : 200
  << date : Fri, 15 Jul 2016 04:47:28 GMT
  << server : Apache/2.2.22 (Debian)
  << cache-control : max-age=0, private, must-revalidate
  << etag : W/"cfa2b7171212da8a9965e6d266df9fca"
  << x-frame-options : SAMEORIGIN
  << x-xss-protection : 1; mode=block
  << x-content-type-options : nosniff
  << x-runtime : 0.014644
  << x-request-id : 15ac1c09-8c24-4908-aac3-1768771e50ea
  << x-powered-by : Phusion Passenger 5.0.28
  << status : 200 OK
  << keep-alive : timeout=5, max=100
  << connection : Keep-Alive
  << transfer-encoding : chunked
  << content-type : application/json; charset=utf-8
  << Body:
{"id":1,"email":"admin@todo.org","name":"Administrator","username":"admin","activated":true,"activated_at":"2016-07-01T19:25:07.000Z","created_at":"2016-07-01T19:24:55.000Z","updated_at":"2016-07-15T04:41:57.000Z","todo_list":[{"id":1,"name":"testname1"},{"id":2,"name":"testname2"}]}
  Flexirest TodoUser#find - Response received 423 bytes
  Flexirest TodoUser:/users/1 - Writing to cache
  Flexirest (42.9ms) TodoUser#find
=> #<TodoUser id: 1, email: "admin@todo.org", name: "Administrator", username: "admin", activated: true, activated_at: "2016-07-01 19:25:07", created_at: "2016-07-01 19:24:55", updated_at: "2016-07-15 04:41:57", todo_list: [#<TodoUser id: 1, name: "testname1">, #<TodoUser id: 2, name: "testname2"], ETag: W/"cfa2b7171212da8a9965e6d266df9fca", Status: 200>
>> TodoUser.find(1)
  Flexirest TodoUser:/users/1 - Trying to read from cache
  Flexirest TodoUser#find - Etag cached copy found with etag W/"cfa2b7171212da8a9965e6d266df9fca"
  Flexirest TodoUser#find - Requesting http://dev0.todo.org/api/v1/users/1
Flexirest Verbose Log:
  Request
  >> GET /api/v1/users/1 HTTP/1.1
  >> If-None-Match : W/"cfa2b7171212da8a9965e6d266df9fca"
  >> Accept : application/hal+json, application/json;q=0.5
  >> Authorization : Token token=[redacted],email=admin@todo.org
  >> Content-Type : application/json; charset=utf-8
  >> Body:
{}
  Response
  << Status : 304
  << date : Fri, 15 Jul 2016 04:47:31 GMT
  << server : Apache/2.2.22 (Debian)
  << connection : Keep-Alive
  << keep-alive : timeout=5, max=100
  << etag : W/"cfa2b7171212da8a9965e6d266df9fca"
  << cache-control : max-age=0, private, must-revalidate
  << Body:
  Flexirest TodoUser#find - Etag copy is the same as the server
  Flexirest (28.1ms) TodoUser#find
**TypeError: no implicit conversion of DateTime into String**
	from /home/dev0/.rvm/gems/ruby-2.3.0/gems/flexirest-1.3.24/lib/flexirest/attribute_parsing.rb:9:in `parse'
	from /home/dev0/.rvm/gems/ruby-2.3.0/gems/flexirest-1.3.24/lib/flexirest/attribute_parsing.rb:9:in `parse_attribute_value'
--snipp

i find a similar error [here](https://github.com/ruhoh/ruhoh.rb/issues/153) they fix it with [Always convert date metadata to string to avoid parse errors](https://github.com/ruhoh/ruhoh.rb/commit/133924aef43e6c48ba5e6578d909c59edc29604c)

looking at the _flexirest/attribute_parsing.rb_
i add `.to_s` and it work fine
```
def parse_attribute_value(v)
   if v.to_s[(/\A(((19|20)\d\d[- \/.](0[1-9]|1[012]|[1-9])[- \/.](0[1-9]|[12][0-9]|3[01]|[1-9]))|((0[1-9]|1[012]|[1-9])[- \/.](0[1-9]|[12][0-9]|3[01]|[1-9])[- \/.](19|20)\d\d))\Z/)]
     Date.parse(v)
   elsif v.to_s[/\A([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?))\Z/]
     DateTime.parse(v.to_s)
   else
     v
   end
end
```

i remove tmp/cache and make the request twice again and it works with no error.
when i make 2nd request it gives the respond output like below
```
=> #<TodoUser id: 1, email: "admin@todo.org", name: "Administrator", username: "admin", activated: true, activated_at: "2016-07-01 19:25:07", created_at: "2016-07-01 19:24:55", updated_at: "2016-07-15 06:43:47", todo_list: [#<TodoUser id: 1, name: "testname1">, #<TodoUser id: 2, name: "testname2"] (unsaved: id, email, name, username, activated, activated_at, created_at, updated_at, todo_list)>
```
there is _inspection_ in the output above _unsaved_ because the result has _@dirty_attributes_?
is this ok? are this `.to_s` is a correct fix?
thanks

**Comment by andyjeffries** [comment]
I would say that isn't the correct fix.  The simple solution would eb to check at the top of `#parse_attribute_value` if `v` is a `DateTime`, `Date` or `Time` already and if so, just return it.

**Comment by andyjeffries** [comment]
Thanks for the bug report again :-)

If you want to create a pull request (with a spec that fails beforehand), please feel free - if not, I'll fix it.

**Comment by mattLummus** [comment]
> i remove tmp/cache and make the request twice again and it works with no error.
when i make 2nd request it gives the respond output like below

@andyjeffries We are seeing some similar weirdness with 1.3.24. After clearing the cache the request works the first time, then subsequent requests fail. Rolling back to 1.3.22 we don't seem to have this issue. We would get a result iterator the first attempt and then either a plain hash or error after, occasionally an empty hash.

**Comment by andyjeffries** [comment]
Can one of you guys check with the github master branch (commit e56f5ee2da4e744093c10821e15669d25a353365) which has a potential fix for this. If it works, I'll release it as 1.3.25.  Thanks.

**Comment by andyjeffries** [comment]
Ping: @mattLummus and @johnmckinght - did the master branch work?

**Comment by andyjeffries** [comment]
OK, I'm assuming so, closing this issue now.
