### ISSUE TITLE
Flexirest Thread Safety

### ISSUE THREAD

**Issue by RuiMochila** [flexirest/flexirest#50]
Hi there,

First of all, thanks for the amazing work with Flexirest.
We've been using it for the past several months, but now that we're moving to Puma webserver, thread safety became a concern and after some digging we realised that it is not safe because it depends a lot on static variables, is there a plan to address this topic?
The relevant use case here would be to have a thread safe base_url, because we have logic that chooses it depending on the situation, and right now it happens that requests get some times called to the wrong base_url, because of that.

Thanks

**Comment by andyjeffries** [comment]
Thank you.

I don't have any current plan to make Flexirest threadsafe. I'm not against accepting PRs that make it so (indeed, I'm for them), it's just that I've never used threading much in Ruby so don't know the best ways of changing the code.

If you have any examples of the changes to make, or any good references, I'm happy to take a look though.

**Comment by alanruth** [comment]
@RuiMochila did you make any progress on this? 

We are about to begin looking at thread safety as we need it similarly as you explained. We would love to have any help from anyone with experience on threading or people who just want to help us on the effort.

**Comment by andyjeffries** [comment]
Sorry @alanruth I don't have much experience of threading, but I'll happily accept a PR with any changes required. For now I'll close this issue though...

**Comment by mvgijssel** [comment]
We're currently doing the following to make the `base_url` configurable
```
  class Base < Flexirest::Base
    def self.connect_using_model(model)
      unless Thread.current[:model].nil?
        fail 'model already set on Thread. Nesting? Or cleanup problem?'
      end

      Thread.current[:model] = model
      yield
    ensure
      Thread.current[:model] = nil
    end

    def self.base_url
      get_model.base_url
    end

    def self.get_model
      model = Thread.current[:model]
      return model unless model.nil?
      fail 'model not set, please use .connect_using_model(model) { ... }'
    end
  end

  class Person < Base
    get :find '/users'
  end

  Person.connect_using_model(OpenStruct.new(base_url: 'some_url')) { Person.find(1) }
```
using `Thread.current` seems to be thread safe (at least on Rails + Unicorn).

But it would be nicer if we could optionally do something like
```
Person.find(client, 1)
```
where the client listens to `base_url` and maybe other methods which are now singletons.

Would something like this be viable @andyjeffries?

**Comment by andyjeffries** [comment]
I think something like the latter would break too much legacy code, unless you can find a really unobtrusive way of doing it.

Generally changes to use Thread.current instead of class instance variables would be accepted.
