### ISSUE TITLE
Question - async nature of calls and processing of results

### ISSUE THREAD

**Issue by alanruth** [flexirest/flexirest#53]
Sorry I couldn't think of another way to title this issue/question.

We leverage Flexirest to handle the integration between two apps. We do some of these calls to the other app via background jobs/sidekiq. Regardless there are times we will call the Flexirest model in one app and then use the values on a native/active record model. 

For example, we call the flexirest object to get a single object from the api. We then instantiate a new native/active record object and populate one of those model attributes with the ID of the flexirest object. When we do this, we get 

```
PG::NotNullViolation: ERROR: null value in column "budget_request_id" violates not-null constraint
```

 due to us having validations on the db level ensuring that value is never null.

When you look at the object in the DB you see that the budget_request_id actually did get populated. My assumption with that is that Sidekiq retried the job and then Flexirest used the cache to grab the object.

Regardless my question is how am I supposed to be doing these types of things? My assumption the Flexirest call is async and thus when i am moving through my logic the values of the flexirest object haven't yet returned or been populated. Thus the reason for the null. Yet what is the best practice on how to do this where we know Flexirest has returned with the values so that we can use them.

Hopefully that makes sense...

**Comment by andyjeffries** [comment]
It doesn't work asynchronously in that way (you can batch multiple requests up in certain cases and have the method return when they're all complete).

So the truth is I don't know why you'd get what you're seeing. Have you tried logging the object resulting from the API call?

**Comment by alanruth** [comment]
sorry for not responded sooner. we got around this in another manner but couldn't figure out why we were having the issue. Thus will post back info or findings. i will close it until then.
