### ISSUE TITLE
Adds singularized record name to parameters

### ISSUE THREAD

**Issue by mikevoets** [flexirest/flexirest#54]
I have the following setup on the client side within a Flexirest class:
```
class ReportService < Flexirest::Base
    request_body_type :json

    get :reports, '/reports',
        :defaults => {
          :filter => {
            :year => 2016
            }
          }
end
```
When I run this, on the server side, the following parameters are entered:
`Parameters: {"filter"=>{"year"=>"2016"}, "report"=>{}}`

What causes this `report` key in the parameters? This `report` key does not appear in the incoming parameters when I do an equivalent curl request:
`curl -X GET 'https://.../reports?filter[year]=2016'`
`Parameters: {"filter"=>{"year"=>"2016"}`

Thanks for your help.

**Edit:**
I found out that the problem goes away when I remove `request_body_type :json` from my Flexirest class.

**Comment by andyjeffries** [comment]
Hey Mike, thanks for the bug report.

My first question is which version of Flexirest are you using? I've only checked this with the latest version.

My steps to reproduce are:

1. Clone the Flexirest repository
2. Within the Flexirest checked out code run `rake c`
3. Paste the following code:

```ruby
class Test < Flexirest::Base
  verbose!
  base_url "http://mockbin.org/bin"

  get :reports, '/a169ea80-2a47-4481-8e4c-e27ca112f44b',
    :defaults => {
      :filter => {
        :year => 2016
        }
      }
end

Test.reports
puts Flexirest::Logger.messages.join("\n")
```

The output (trimmed) of this is:

```
Flexirest Verbose Log:
  Request
  >> GET /bin/a169ea80-2a47-4481-8e4c-e27ca112f44b?filter%5Byear%5D=2016 HTTP/1.1
```

As you can see, there's no empty "report" parameter in there. I don't know how long mockbin will cache the request for, but you may be able to see it "server-side" here too http://mockbin.org/bin/a169ea80-2a47-4481-8e4c-e27ca112f44b/log

Can you create a small Rails app and shove it on github that runs with `rails server` that makes a Flexirest request to itself that demonstrates the problem?

**Comment by mikevoets** [comment]
Hi Andy,

Thanks for your quick response.

As you suggested, I created a small Rails app here https://github.com/mikevoets/dummy_blog. In this app I created a ReportsController with an index method. This method responds with a JSON object containing the request parameters.

When I start up the dummy app on port 3001, and I use the following code to test:

```
class Test < Flexirest::Base
  verbose!
  base_url "http://localhost:3001"

  request_body_type :json

  get :reports, '/reports',
    :defaults => {
      :filter => {
        :year => 2016
        }
      }
end

Test.reports
puts Flexirest::Logger.messages.join("\n")
```
I get the following report:
```
  Flexirest Test#reports - Requesting http://localhost:3001/reports?filter%5Byear%5D=2016
Flexirest Verbose Log:
  Request
  >> GET /reports?filter%5Byear%5D=2016 HTTP/1.1
  >> Accept : application/hal+json, application/json;q=0.5
  >> Content-Type : application/json; charset=utf-8
  >> Body:
{}
  Response
  << Status : 200
  << x-frame-options : SAMEORIGIN
  << x-xss-protection : 1; mode=block
  << x-content-type-options : nosniff
  << content-type : application/json; charset=utf-8
  << etag : W/"e1b027af4fe29733ac5a730162e08d4a"
  << cache-control : max-age=0, private, must-revalidate
  << x-request-id : 58458cf6-509f-42c5-8b93-640bb5d772ee
  << x-runtime : 0.088897
  << transfer-encoding : chunked
  << Body:
{"filter":{"year":"2016"},"controller":"reports","action":"index","report":{}}
  Flexirest Test#reports - Response received 78 bytes
  Flexirest (147.3ms) Test#reports
```
As you can see, the parameters include a `report: {}`. I discovered that, when I remove the `request_body_type :json` from the Test Flexirest class, the problem goes away.

Is this normal behavior? Did I misunderstand `request_body_type :json`? I thought this function was equivalent to adding `Content-Type: application/json` headers. But I see now it isn't.

**Comment by andyjeffries** [comment]
Hi Mike,

You're absolutely right it's the `request_body_type` causing a problem. What this is used for is how to encode the bodies of requests. The default is "form-encoded", but some APIs want a JSON body for the request. You don't need to set it for the `Content-Type` header to be sent (that's default).

This is a bug though, because this should have been ignored given that it's a GET request (and therefore shouldn't really have a body). I'll fix that bug. However, it's definitely correct for you to remove that line. If you don't know that you need to use it (because your API wants JSON bodies for requests) then it's not correct to put it in.

**Comment by mikevoets** [comment]
Ah, since I am also doing some POST requests in my Flexirest class, and the API accepts a JSON object only, I will still need `request_body_type :json`. 

Is there a way to workaround this bug until your fix gets released? For example, some `before_request` method?

**Comment by andyjeffries** [comment]
I've just released 1.3.27 on Rubygems, please try that and let me know if it fixes it.

**Comment by andyjeffries** [comment]
If it doesn't https://github.com/flexirest/flexirest#body-types also gives an example of how to only specify it on your POST methods (or set it as the default, then reset it to `:form_encoded` on your GET methods).

However, I hope 1.3.27 will fix it.

Does your API complain about unexpected parameters then?

**Comment by mikevoets** [comment]
Thank you! The fix worked very well. Thanks for the link as well, very interesting.

Yes, the API is rather strict. It white-lists parameters, so if it sees a parameter that is not expected, it'll complain.
