### ISSUE TITLE
Perform caching false does not work as expected

### ISSUE THREAD

**Issue by mikevoets** [flexirest/flexirest#55]
Hi,

When I define `perform_caching false` in a Flexirest::Base class, it is still caching all results when the responding service includes an ETag. I don't know for other Rails versions, but if the server is a Rails 5 API application, responses will always include an ETag.

I am using Flexirest 1.3.27.

I am printing the response in a proxy class:

`#<Faraday::Response:0x00000008519fc0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body="" @url=#<URI::HTTP:0x0000000850f4d0 URL:###> @request=#<Faraday::RequestOptions timeout=60> @request_headers={"User-Agent"=>"Flexirest/1.3.27", "If-None-Match"=>"3cef065214a766fedf6c09275645a193", "Accept"=>"application/json", "X-Api-Key"=>"0KadWOPf8x3Mb7zSLfZE1Qtt"} @ssl=#<Faraday::SSLOptions (empty)> @response=#<Faraday::Response:0x00000008519fc0 ...> @response_headers={"x-frame-options"=>"SAMEORIGIN", "x-xss-protection"=>"1; mode=block", "x-content-type-options"=>"nosniff", "etag"=>"3cef065214a766fedf6c09275645a193", "cache-control"=>"max-age=0, private, must-revalidate", "x-request-id"=>"9e20d434-5719-4ce8-9208-ce1d814ddf99", "x-runtime"=>"0.784712", "connection"=>"close"} @status=304 @reason_phrase="Not Modified">>`

I even tried on the server side to send back 200 OKs instead of 304 Not Modified (while still sending back the same ETag) to see if this affects something, but it didn't matter at all. The response is still as above (304). Even though I explicitly send back a 200 OK:

`Completed 200 OK in 738ms (Views: 6.5ms | ActiveRecord: 0.6ms)`

There seem to be strange things going on here. It seems to me that the client is basing it's response code on if the sent ETag is the same as the received ETag (making it 304), and not on the actual response code (200). Also, it seems to be ignoring the `perform_cache false`.

Let me know if you need a more elaborate explanation or help.

**EDIT:** The workaround I have for this right now, is defining `Flexirest::Base.perform_caching = false` in an initializer (or production.rb).

**EDIT2:** Could I have this issue because I am running my client in development environment?

**Comment by andyjeffries** [comment]
You're right, there was a bug with setting `perform_caching` on the `Flexirest::Base` object. Fixing now and will release about a minute afterwards (v1.3.29)

**Comment by andyjeffries** [comment]
df342ba
