### ISSUE TITLE
Defining proxy class in parent class does not work

### ISSUE THREAD

**Issue by mikevoets** [flexirest/flexirest#56]
I have the following setup:

```
# service/base.rb
module Service
  class Unwrapper < Flexirest::ProxyBase
    get %r(.*) do
      response = passthrough
      translate(response) do |body|
        ...
      end
    end
  end

  class Base < Flexirest::Base
    proxy Service::Unwrapper
    ...  
  end 
end

---
# service/report.rb
module Service
  class Report < Service::Base
    ...
  end
end
```

However, the proxy does not work when I define it in the parent class. It initializes it correctly, but the regexp-method within the Unwrapper proxy does not fire. It works only if I put the proxy statement it in the Service-class, but this is not very DRY. I will be having lots of classes under the Base class.

I tried the following, but it didn't work either:

```
# service/base.rb (within the Base class)
...
def self.included(base)
  base.class_eval do
    proxy Service::Unwrapper
  end
end
```

Am I overlooking something here? Should I define the proxy class different?

**Comment by andyjeffries** [comment]
I think the proxy functionality is rarely used, so to be honest I can't imagine it's worth me spending much time refactoring this to be inheritable. If you want to submit a pull request rather than having duplication of `proxy Service::Unwrapper` in each class, I'd be happy to review/merge it.

**Comment by mikevoets** [comment]
I'll look into it. Thanks for your consideration.
