### ISSUE TITLE
Filename too long on caching response

### ISSUE THREAD

**Issue by mikevoets** [flexirest/flexirest#57]
Hi,

In some cases, the request URI gets big. When it receives the response from the service, and it wants to cache this, it sometimes yields the following exception:

( I modified it a bit in order to hide the actual path, but you'll get the point )
`Errno::ENAMETOOLONG: File name too long - /very/long/path/to/rails/project/tmp/cache/module_name%3A%3Aflexi_rest_class_name%3A%2F_method%3Ffilter%255Bsequence_number%255D%3D1012%26filter%255Byear%255D%3D2014%26include%3Djournals20161119-13300-p21hbf.lock`

**Comment by andyjeffries** [comment]
What's your suggestion for this? I could SHA256 the request details, but in most people's systems they don't have a "/very/long/path/to/rails/project" and in production they don't stick with the default filesystem cache so it becomes a non-issue.

**Comment by mikevoets** [comment]
Yes, you're right. It's probably not worth it to spend too much time into this.
