### ISSUE TITLE
`prepare_url` deletes much-needed GET/POST params

### ISSUE THREAD

**Issue by tricon** [flexirest/flexirest#59]
[Consider this line](https://github.com/flexirest/flexirest/blob/bf23b0165e2cf19e959a1ee9ddef60b3189efc17/lib/flexirest/request.rb#L273) and the following URL structure: `/conacts/:id`.

An API I am integrating with needs ID in the URL and the post body as it matches the two for "verification". As the aforementioned line deletes this from `get_params` and `post_params`, my only reasonable option is to pull it from the params and re-include it with a proxy.

Shouldn't we reconsider the deletion of such attributes?

**Comment by andyjeffries** [comment]
It's difficult because most APIs won't require it and it's cleaner to not duplicate the parameter. I think a proxy is the right solution for this unusual API.
