### ISSUE TITLE
JSON-API?

### ISSUE THREAD

**Issue by l8nite** [flexirest/flexirest#64]
I was evaluating this as an alternative to Her (https://github.com/remiprev/her/) - I can't find any mention of jsonapi (http://jsonapi.org) in the docs, is it supported?

**Comment by andyjeffries** [comment]
There's no current support for it, but I'd accept a PR if you wanted to implement it. I think it's partway there with the existing support for HAL responses.

**Comment by mikevoets** [comment]
At the moment I am implementing support for jsonapi. I will be submitting a PR in a few days.

**Comment by andyjeffries** [comment]
@mikevoets 's PR has been merged in as of v1.4.0.
