### ISSUE TITLE
Dirty tracking with selective attributes for PATCH?

### ISSUE THREAD

**Issue by eshork** [flexirest/flexirest#71]
How about the optional addition of Mongoid style dirty tracking for model attributes, so that future updates (PATCHes) to an endpoint might only contain the attributes that have been changed, rather than the current full object.

Given the current loose implementation style of this gem, this feature might be best implemented as an optional setting on a per-action basis, much like how `:ignore_root` currently works.

**Comment by andyjeffries** [comment]
It already tracks dirty attributes in `base.rb`, it just doesn't use them in a PATCH call. Happy to accept a PR...

**Comment by eshork** [comment]
Fair enough. I'll take a deeper look and see what I can do. Just wanted to check in before I committed effort to something that wasn't PR worthy for the project.

**Comment by andyjeffries** [comment]
This is definitely a worthy PR. I'll close this issue now, but feel free to raise a PR when you're ready (even if you just want comments on the code early on)
