### ISSUE TITLE
URL double encoding

### ISSUE THREAD

**Issue by davidtolsma** [flexirest/flexirest#73]
I have a URL with a name that has a '/' (forward slash) in the name. So i escape it to %2F before making the call. Flexirest errors with a 404. I print out the exception it appears to be double encoded the %2F to %252. It appears that Flexirest is encoding the URL when the value is %2F, but doesn't do it with a '/'.

**Comment by davidtolsma** [comment]
Looking at the code in the request.rb file on line 310
https://github.com/flexirest/flexirest/blob/a98f4048aebb260e06474befd485eaba6ee6ef73/lib/flexirest/request.rb#L310

The URI.escape method is used. When i try

URI.escape('abc/def') => "abc/def"
URI.escape('abc%2Fdef') => "abc%252def"

I understand why the / is not escaped, but if it's already escaped then URI.escape double encodes it.

**Comment by andyjeffries** [comment]
Released as 1.3.35, thanks for the issue.

**Comment by davidtolsma** [comment]
Thanks. This option to encode the URI is useful, possible provide as an option when it becomes needed.
