### ISSUE TITLE
Plain Request with Basic-Auth

### ISSUE THREAD

**Issue by rgisiger** [flexirest/flexirest#80]
Hello,

I have a class wich has its own base url, username and password for Basic-Auth authentication, and I try to get the content as string at the following URL : 

`self._plain_request( self.base_url + a_dynamic_path )`

But the Basic-Auth is something like skipped in the request process. I suspect something near lines 378-379 to use a local 'base_url' variable which is not yet defined. 

```
base_url.gsub!(%r{//(.)}, "//#{username}:#{password}@\\1") if username && !base_url[%r{//[^/]*:[^/]*@}]
connection = Flexirest::ConnectionManager.get_connection(base_url)
```

Using either `@base_url` or `self.base_url` is working but as I don't know what could be influenced after that modification, I prefer to let you know about it.

By the way, I didn't find any public URL with basic-auth and rendering in text/plain to show you, sorry for that.

Thanks for your answer.

**Comment by andyjeffries** [comment]
If you're passing in a complete URL, why can't you insert the username/password in there yourself when building the URL string? Seems like you're skipping using Flexirest's built in `base_url` handling (which includes the username/password) but want that functionality. Sorry I can't be of more help, but it seems you can insert those details into your custom `base_url` or use the built in functionality and there's nothing I need to change.
