### ISSUE TITLE
Render user entered data in rescue block if update fails

### ISSUE THREAD

**Issue by tusharsawant2090** [flexirest/flexirest#81]
Hi,

I have rails  5.0.1 app (App 1) working which uses another Rails API for database operations.
App 1 is not using active record. 
App 1 is using flexirest for Api calls.

When create or update method is called, all the data is sent to rails api in json format.
i want when api throws any error, it should be catch in rescue block and also the data which user entered before submit click should be render after rescue using `render :edit` (for update) or `render :new` (for create)

here is my code 

```ruby
def update
    respond_to do |format|
      begin
        if @booking.update({id: @booking.booking.id, booking: booking_params})  
          format.html { redirect_to excel_front_innstats_path, notice: display_notice(t("label.detailed_reservation.reservation")) }
        else
          format.html { render :edit }
        end
      rescue => e
        #here assign the booking object with user entered data, 
        #so that the form will not loose the data, if exception occurs
        flash_error_message(:error, e.result)
        format.html { render :edit }
      end  
    end
  end
```

**Comment by andyjeffries** [comment]
I don't quite understand what the issue you're raising is? Flexirest will raise an error as described in https://github.com/flexirest/flexirest#httpparse-error-handling if the API it's calling uses a non-2xx/3xx status, which you can rescue from and handle however you want, including rendering Rails actions or whatever. If you can be more descriptive on what the error/problem is with Flexirest then maybe I can help, but I can't see anything to fix our side.
