### ISSUE TITLE
Possible to do a find on collection?

### ISSUE THREAD

**Issue by heldopslippers** [flexirest/flexirest#82]
Hi There, 

Just wondering if this would be possible. 
I am doing a call for a user, which also returns multiple shops. 

Currently it isn't possible to do a: current_user.shops.find(1). 
In my case it returns an enumerator with the shops. 

Is there a way to query by id without doing: Shop.find(2) ? 
As I don't want another call to the api.

**Comment by andyjeffries** [comment]
You can't use find on the `shops` part of the results because there's no special meaning to `find` - it's just that you've mapped it to an API endpoint. You could use `detect` on shops because `ResultIterator` will act like any enumerable:

```ruby
current_user = User.find(session[:user_id])
shop = user.shops.detect {|shop| shop.id == 1 }
```

Something like that.

**Comment by heldopslippers** [comment]
Ah, Yes thats nice.
I came up with: 
`user.shops.find {|shop| shop.id == 1}`
