### ISSUE TITLE
Small helper for people who need to filter

### ISSUE THREAD

**Issue by heldopslippers** [flexirest/flexirest#85]
As I need to filter results sometime, I made the following function. 
just leaving it here if people are looking for it: 

```
class Flexirest::ResultIterator
  def where(hash={})
    self.items.select do |object|
      select = true
        hash.each do |k, v| 
          select = false if object[k] != v
        end
        select
      end
   end
end
```

You can use it as follow: 
`People.all.where(admin: true)`

**Comment by andyjeffries** [comment]
I've merged this in to the core Flexirest gem, and enhanced it slightly to also allow for regex matching. Thanks for this, very nice.

https://github.com/flexirest/flexirest#filtering-result-lists
