### ISSUE TITLE
Using the request.post? method

### ISSUE THREAD

**Issue by samstarling** [flexirest/flexirest#86]
Hello – I noticed that in the documentation, you have a block of code like this:

```
  before_request do |name, request|
    if request.post? || name == :save
      id = request.post_params.delete(:id)
      request.get_params[:id] = id
    end
  end
```

However, it looks like `.post?` isn't a method on request. Is this something I need to include specifically, or is there another way I could get this? Thanks!

**Comment by andyjeffries** [comment]
Sorry about that, don't know how it was missing. Can you try v1.5.9 (just released) and should all be resolved.

**Comment by samstarling** [comment]
@andyjeffries No problem – just given it a go and it works perfectly. Thanks!

**Comment by andyjeffries** [comment]
Great, thanks for reporting the problem. Glad I could fix it for you.
