### ISSUE TITLE
Writing a Proxy class to wrap all attributes

### ISSUE THREAD

**Issue by samstarling** [flexirest/flexirest#87]
I'm working with an API where all PUT and POST requests have to wrap all the attributes in a particular root element. So, for example, if I PUT to `/people`, then the body has to look like:

```
{
  "person": {
    "name": "Sam",
    "location": "Outer space"
  }
}
```

This is the case for all models. At the moment, I'm doing this on a per-model basis:

```
class PersonProxy < Flexirest::ProxyBase
  post "/people" do
    body({ person: post_params }.to_json)
    passthrough
  end
end

class Person < Flexirest::Base
  get :all, '/people'
  post :create, '/people'
  proxy PersonProxy
end
```

Is there a nicer way that I could do this for every model? Thanks in advance for any advice.

**Comment by andyjeffries** [comment]
There wasn't, there's an easier way now (as of 1.6.0): https://github.com/flexirest/flexirest#root-elements

**Comment by andyjeffries** [comment]
It's not for every model, but at least you can specify it when mapping methods.

**Comment by andyjeffries** [comment]
```ruby
class Person < Flexirest::Base
  get :all, '/people'
  post :create, '/people', wrap_root: "person"
end
```

**Comment by samstarling** [comment]
Aha, this is perfect – thanks! I hadn't quite read this far in the documentation, and I assumed it was just for when the JSON payload was being read. Thanks again for the speedy response, much appreciated.

**Comment by andyjeffries** [comment]
It wasn't in the documentation - I just added the feature ;-)

**Comment by samstarling** [comment]
Ah, wow, even better. Thank you!
