### ISSUE TITLE
Custom validates method throwing an exception

### ISSUE THREAD

**Issue by samstarling** [flexirest/flexirest#88]
Hello, me again! I'm writing a custom validation, but it's throwing an error:

```
    validates :amount do |object, name, value|
      unless (0..500).include? value
        object._errors[name] << "must be between zero and 500"
      end
    end
```

This throws a `ArgumentError (You need to supply at least one validation)`. Is there something I'm doing wrong?

**Comment by andyjeffries** [comment]
I can't reproduce this. My attempt:

1. Clone the Flexirest repo (`git clone https://github.com/flexirest/flexirest.git`)
2. Change to the flexirest folder (`cd flexirest`)
3. Install any dependencies (`bundle install`)
4. Run an interactive console (`rake c`)
5. Paste the following:

```ruby
class Loan < Flexirest::Base
  base_url "https://requestb.in"
  post :create, "/yulx35yu"

  validates :amount do |object, name, value|
    unless (0..500).include? value
      object._errors[name] << "must be between zero and 500"
    end
  end
end

loan = Loan.new(name: 1)
# next line raises Flexirest::ValidationFailedException
loan.create

puts loan.full_error_messages
# => amount must be between zero and 500
```

All works as expected.

**Comment by andyjeffries** [comment]
By the way, based on your feedback I've now made a new issue template based on the worked through example of how I tried to reproduce it. So thanks for making me think about doing that.

**Comment by samstarling** [comment]
Hmm, I'm stumped – you're right. Let me see if I can reproduce it in a rake console in your repository. And thanks for the template, that's really useful.

**Comment by samstarling** [comment]
Ah, I've realised what I'm doing:

```ruby
class Loan < Flexirest::Base
  base_url "https://requestb.in"
  post :create, "/yulx35yu"

  validates :amount, presence: true, numericality: true
  validates :amount do |object, name, value|
    unless (0..500).include? value
      object._errors[name] << "must be between zero and 500"
    end
  end
end

loan = Loan.new(amount: 1000)
loan.create
```

**Comment by samstarling** [comment]
I'll re-open this if I discover what I'm doing wrong.
