### ISSUE TITLE
Using wrap_root on create

### ISSUE THREAD

**Issue by samstarling** [flexirest/flexirest#89]
### Expected behaviour

I have a model with the following create:

```
post :create, '/clients', wrap_root: 'client'
```

It sends the data to the server wrapped in a client root element (which is perfect), and then the server responds to let me know the object it created (with the ID it assigned), also wrapped in a root element:

```
{ "client": { "id": "123", "name": "Sam" } }
```

However, it doesn't then parse those fields into the model, if I use something like this:

```
client = Client.new(name: "Sam")
created_client = client.create
```

Then `created_client.id` and `.name` are nil, and the object prints like this, which makes it look like it is incorrectly nested:

```
#<Client client: #<Client id: "123", state: "Sam">
```

### Desired behaviour

The `create` method would parse the response and set the attributes appropriately.

### How to reproduce

See above.

**Comment by andyjeffries** [comment]
As per https://github.com/flexirest/flexirest/blob/master/docs/root-elements.md the two mechanisms are separate (outbound wrapping and inbound root ignoring). So what you'd probably need to use is:

```ruby
post :create, '/clients', wrap_root: 'client', ignore_root: 'client'
```

Please give that a try and re-open the issue if you still have issues.

**Comment by samstarling** [comment]
Aha, sorry that is missed it – this is in plain sight! Thanks for the fast reply.
