### ISSUE TITLE
Configuring per-user authentication options

### ISSUE THREAD

**Issue by samstarling** [flexirest/flexirest#91]
I'd like to base the `username` and `password` I use on the `current_user`. You could use something like `RequestStore` for this. For example:

```
class MyController
  before_action :authenticate_user
  before_action :set_credentials

  def set_credentials
    RequestStore.store[:api_username] = current_user.api_username
  end
end

class MyModel < Flexirest::Base
  username RequestStore.store[:api_username]
end
```

I thought about doing this in `before_request`, but the username can't be changed there. Is there a better way of doing this?

**Comment by andyjeffries** [comment]
There wasn't...

There is now!

`username` and `password` now take a proc/block and can therefore retrieve a user based on the current request and/or Flexirest object.

See v1.6.6 or above's [Authentication docs](https://github.com/flexirest/flexirest/blob/master/docs/authentication.md#basic-authentication)
