### ISSUE TITLE
Transparently mapping and renaming attributes

### ISSUE THREAD

**Issue by samstarling** [flexirest/flexirest#93]
I'm dealing with an API that returns data with some less-than-ideal names. Take this as a (slightly exaggerated) example:

```
GET /people/1
{ 
  "person": {
    "fn": "Sam",
    "ln": "Starling"
  }
} 
```

If I have a model like this:

```
class Person < Flexirest::Base
  alias_attribute :first_name, :fn
  alias_attribute :last_name, :ln
end
```

That's nice, because then I can just call `Person.find('1').first_name`, and benefit from sensible naming.

However, I'm struggling to work out a good way to rename the attributes on the other side. If I use `Person.create(first_name: 'Sam')`, then the request ends up being sent with `first_name` and not `fn`, as the API expects. Is there a nice way of doing this translation in both directions?

Currently I've written a proxy that re-maps the names, but that's endpoint-specific. I'd really like this to hold for (for example) all `post`/`put`/`patch` endpoints that the model has, to try and reduce duplication. Is there a nicer way of doing this?

For what it's worth, this API requires updates with `request_body_type: :json`. Can I override `to_json`?

**Comment by andyjeffries** [comment]
So if `alias_attribute` accepted an option `both_ways: true` that then also remapped them on the way back to the server?

I don't understand what you mean about overriding `to_json`? Why is that necessary when there's already support for sending JSON bodies? https://github.com/flexirest/flexirest/blob/master/docs/body-types.md

**Comment by samstarling** [comment]
Having a `both_ways` option would make a lot of sense for me. To rephrase what I meant: could I override `to_json` on my model to control what's sent back to the server, or does Flexirest turn my models into JSON some other way?

**Comment by samstarling** [comment]
@andyjeffries One other question that's slightly related: can I access the original model from a proxy class?

**Comment by andyjeffries** [comment]
Sorry @samstarling I'd missed your last comments. I don't think it would be easy to override `to_json` as this is called on a Hash. If you want to control what's sent back to the server, you kind of need the same thing as the `proxy` behaviour, but in reverse. There's no support for that, but happy to receive pull requests.

You can't access the original model from within a proxy, the proxy is only passed a request object.
