### ISSUE TITLE
Validating associated models

### ISSUE THREAD

**Issue by samstarling** [flexirest/flexirest#94]
### Expected behaviour

When I call `.valid?` on a model, the associated models should also be checked, or there should be a way (perhaps similar to [validates_associated](https://apidock.com/rails/ActiveModel/Validations/ClassMethods/validates_associated)).

```
class Address < Flexirest::Base
  validates :town, presence: true
end

class Person < Flexirest::Base
  validates :name, presence: true
  has_many :addresses, Address
end

a = Address.new
a.valid?
# Returns false, all good

p = Person.new(name: "Sam", addresses: a)
puts p.valid?
# Returns true, but contains an invalid address
```

### Desired behaviour

There should be a way to signal that relations should be checked for validity.

### How to reproduce

See the example above, which you can paste into a Flexirest console.

**Comment by andyjeffries** [comment]
The relationship work is more about how to instantiate objects in the responses. I'll be happy to take a PR to fix this, but don't have the time to make it even closer to ActiveRecord when it comes to relationships. In the absence of a PR I'll close this issue, but if you're willing to send a PR please re-open it :-)
